apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2024-10-17T103303Z
  name: policy-exc-req-k6827w6206f-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-capabilities
    ruleNames:
    - autogen-adding-capabilities
    - adding-capabilities
  - policyName: disallow-privileged-containers
    ruleNames:
    - autogen-privileged-containers
    - privileged-containers
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  match:
    any:
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - kindnet-4rz8k
        - kube-proxy-d9xwj
        - etcd-test-sachin-control-plane
        - kube-controller-manager-test-sachin-control-plane
        - coredns-76f75df574-njzbw
        - kube-apiserver-test-sachin-control-plane
        - kube-scheduler-test-sachin-control-plane
        - coredns-76f75df574-s9zwf
        namespaces:
        - kube-system
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-76f75df574
        namespaces:
        - kube-system
