apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2025-04-29T124812Z
  name: policy-exc-req-h5778u2548t-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
    - privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-capabilities
    ruleNames:
    - autogen-adding-capabilities
    - adding-capabilities
  - policyName: restrict-automount-sa-token
    ruleNames:
    - validate-automountServiceAccountToken
    - autogen-validate-automountServiceAccountToken
  - policyName: disallow-privileged-containers
    ruleNames:
    - autogen-privileged-containers
    - privileged-containers
  - policyName: restrict-volume-types
    ruleNames:
    - autogen-restricted-volumes
    - restricted-volumes
  - policyName: disallow-host-namespaces
    ruleNames:
    - autogen-host-namespaces
    - host-namespaces
  - policyName: disallow-host-path
    ruleNames:
    - autogen-host-path
    - host-path
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
    - autogen-adding-capabilities-strict
    - adding-capabilities-strict
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
    - check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-5d78c9869d
        namespaces:
        - kube-system
    - resources:
        kinds:
        - DaemonSet
        names:
        - kube-proxy
        - kindnet
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - kube-proxy-vrdns
        - kube-scheduler-kind-control-plane
        - kube-apiserver-kind-control-plane
        - coredns-5d78c9869d-tkgs6
        - kindnet-7qnnj
        - kube-controller-manager-kind-control-plane
        - etcd-kind-control-plane
        - coredns-5d78c9869d-vcxrp
        namespaces:
        - kube-system
