apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2026-01-16T181943Z
  name: policy-exc-req-g6049r8297s-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user
    - autogen-run-as-non-root-user
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - autogen-adding-capabilities-strict
  match:
    any: []
