apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 2026-01-14T191959Z
  name: policy-exc-req-i3482x8239w-0
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  match:
    any: []
